# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3982e1e2b0d4d1914f7280baafff1e95d1e0bc149720d358bb4722ce38ba3dabff9b74b527341f83fb7643e5138f2445fb61483408aa2707ca6549c9c7ad3b9c

test:
  secret_key_base: b8ef800c522a02cb857aea2181359695bf7fc7e5ae4f655feab68cf7a2f54f899fe952897705b801b61f8016b67e4cf17c17bab089eee5b215bee3e37100434c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
